name: Merge Runner

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - master


jobs:
  test-quee:
    name: Test Quee In-Memory
    uses: ./.github/workflows/build-and-test.yml
    with:
      CONFIGURATION: Release
      DOTNET_VERSION: 10.0.x
      PROJECT_PATH: './test/Quee.Memory.Tests/Quee.Memory.Tests.csproj'
